### ISSUE TITLE
2.x vs 1.5.x  

### ISSUE THREAD

**Issue by mylovetop** [piomin/sample-spring-cloud-webflux#2]
1.5.x  
customer-service as follows:
eureka.client.serviceUrl.defaultZone=http://localhost:1234/eureka/
eureka.instance.perferIpAddress=true
eureka.instance.instance-id=${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}
eureka.instance.hostname=${spring.cloud.client.ipAddress}

2.x  customer-service no above that,   

in   application.yml of customer-service  only the config  as follows:
server:
  port: 2222
  
spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://192.168.99.100/test

then  auto registration to discovery-service.  account-service the same.

  What are the differences  between 2.x to  1.5.x  on spring cloud?

thanks!

**Comment by ramazansakin** [comment]
Hi @mylovetop ,

Can you review this page? I think you can find you answer here:
https://altkomsoftware.pl/en/blog/spring-boot-migration-java/

**Comment by piomin** [comment]
updated to the latest
